### ISSUE TITLE
env var consistency

### ISSUE THREAD

**Issue by iloire** [wiseNhammer/watchmen-plugin-nodemailer#1]
I wonder if it could be good idea to maintain consistency with the other watchmen env vars. Like using

```
WATCHMEN_AUTH_NODEMAILER_USER
```

instead of

```
AUTH_NODEMAILER_USER
```

That should make easier to maintain an independent watchmen configuration.

**Comment by emilyhorsman** [comment]
Good call.

**Comment by emilyhorsman** [comment]
Fixed! Version bumped to `0.2.0` and published to the registry https://www.npmjs.com/package/watchmen-plugin-nodemailer
